<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-5AP2L8LH" failures="1" tests="6" name="Personal loan" time="0.065" errors="0" timestamp="2021-10-02T21:45:16 EDT">
  <testcase classname="Test.day1" name="Demo" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.day1.Demo(day1.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="Test.day2" name="parameter" time="0.004"/>
  <testcase classname="Test.day2" name="ploan" time="0.001"/>
  <testcase classname="Test.day4" name="MobileLoginhome" time="0.001"/>
  <testcase classname="Test.day4" name="WebLoginhome" time="0.003"/>
  <testcase classname="Test.day4" name="LoginAPIcarloanhome" time="0.001"/>
  <testcase classname="Test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
